name: Hue
main: com.dylan.hue.HuePlugin
version: 0.1.1
api-version: 1.14
commands:
    hue:
        description: Sets your desired chat color.
        usage: /hue <red|gold|darkred|etc.>
        permission: hue.use