name: Hue
main: com.dypo.hue.HuePlugin
version: 1.2.5
api-version: 1.15
commands:
    hue:
        description: Sets your desired chat color.
        usage: /hue <red|gold|darkred|etc.>
        permission: hue.use