name: Hue
main: com.dylan.hue.HuePlugin
version: 1.2.0
api-version: 1.14
commands:
    hue:
        description: Sets your desired chat color.
        usage: /hue <red|gold|darkred|etc.>
        permission: hue.use